### ISSUE TITLE
Crash when running with wigle-wifi-wardriving.

### ISSUE THREAD

**Issue by xingweitian** [vehiloco/crypto-checker#4]
If use Checker Framework 3.3.0, it will crash when running with [wigle-wifi-wardriving](https://github.com/xwt-benchmarks/wigle-wifi-wardriving).

Travis log: https://travis-ci.org/github/vehiloco/crypto-checker/jobs/671024587

TODO: come up with a minimum test case, then report to typetools/checker-framework.

**Comment by wmdietl** [comment]
I think we introduced this bug with https://github.com/typetools/checker-framework/pull/3087
I thought there recently was another bug with the same crash, but I can't find it now.
You should be able to repro with just the Value Checker.

**Comment by xingweitian** [comment]
Already opened this issue in typetools, this one can be closed.
